Xcode 9.4.1 (9F2000)

diff --git a/Xcode.app/Contents/Applications/Application Loader.app/Contents/itms/bin/iTMSTransporter b/Xcode.app/Contents/Applications/Application Loader.app/Contents/itms/bin/iTMSTransporter
--- a/Xcode.app/Contents/Applications/Application Loader.app/Contents/itms/bin/iTMSTransporter
+++ b/Xcode.app/Contents/Applications/Application Loader.app/Contents/itms/bin/iTMSTransporter
@@ -83,7 +83,6 @@ DEFAULT_JVM_OPTIONS="-DWORootDirectory=\"${WOROOT}\" -DWOLocalRootDirectory=\"${
 JVM_OPTIONS="-Xmx2048m -Xms1024m -Djava.awt.headless=true -Dsun.net.http.retryPost=false -Dhttps.protocols=TLSv1.1,TLSv1.2"
 JVM_EXECUTABLE=java
 APPLICATION_CLASS=com.apple.transporter.launcher.Application
-JAVA9_OPTS=""
 if [ "${PLATFORM_DESCRIPTOR}" = "MacOS" ]
 then
     JVM_EXECUTABLE="${RELATIVE_JVM}"
@@ -110,7 +109,7 @@ VERSION_NUM=$(echo "${RAW_VERSION_NUM}" | awk '/^java|openjdk version/ {ver=$NF;
 if [ "${VERSION_NUM}" = "" ]
 then
     # java -version either didn't return anything, or it returned something that we didn't expect
-    echo Java 1.8 or higher is required. Please install Java. 1>&2
+    echo Java 1.7 or higher is required. Please install Java. 1>&2
     if [ -f "{JAVA_EXECUTABLE}" ]
     then
         echo "output of: \"${JAVA_EXECUTABLE}\" -version" 1>&2
@@ -119,25 +118,19 @@ then
         echo "unable to find ${JAVA_EXECUTABLE}" 1>&2
     fi
     exit 1
-# see if they are using 1.8 or higher
-JAVA_VERSION_MAJOR=$(echo "${VERSION_NUM}" | sed -e 's/^\([0-9][0-9]*\).*$/\1/')
+# see if they are using 1.7 or higher
 JAVA_VERSION_MINOR=$(echo "${VERSION_NUM}" | sed -e 's/^1\.\([0-9][0-9]*\).*$/\1/')
-#if they aren't using 1.8 or higher, display an error and exit
-if [ "${JAVA_VERSION_MAJOR}" = "9" ]
-then
-    # do nothing here, they are running 9
-    USING_JAVA_9="true"
-    JAVA9_OPTS="--add-modules=java.sql,java.xml,java.xml.bind"
-elif [ "${JAVA_VERSION_MINOR}" = "" ]
+#if they aren't using 1.7 or higher, display an error and exit
+if [ "${JAVA_VERSION_MINOR}" = "" ]
 then
     # java -version returned something, but didn't match our sed expression.
-    echo "Java 1.8 or higher is required. Currently, java ${VERSION_NUM} is the default java version. Please upgrade." 1>&2
+    echo "Java 1.7 or higher is required. Currently, java ${VERSION_NUM} is the default java version. Please upgrade." 1>&2
     exit 1
 #this is separate from the previous "if" to avoid a shell script error when the env variable is empty
-if [ "${JAVA_VERSION_MAJOR}" = "1" ] && [ "${JAVA_VERSION_MINOR}" -lt 8 ]
+if [ "${JAVA_VERSION_MINOR}" -lt 7 ]
 then
-    # java -version returned 1.x, where x < 8
-    echo "Java 1.8 or higher is required. Currently, java ${VERSION_NUM} is the default java version. Please upgrade." 1>&2
+    # java -version returned 1.x, where x < 7
+    echo "Java 1.7 or higher is required. Currently, java ${VERSION_NUM} is the default java version. Please upgrade." 1>&2
     exit 1
 # All -D flags need to be passed to the JVM before the application class is
 # specified on the command line, so process $@ to copy such arguments to
@@ -198,4 +191,4 @@ for arg in "$@"
     esac
 done
 # Launch the application.
-eval exec "\"${JAVA_EXECUTABLE}\" ${JAVA_EXECUTABLE_ARGS} ${JAVA9_OPTS} -jar ./lib/itmstransporter-launcher.jar ${COMMAND_LINE_ARGS}"
+eval exec "\"${JAVA_EXECUTABLE}\" ${JAVA_EXECUTABLE_ARGS} -jar ./lib/itmstransporter-launcher.jar ${COMMAND_LINE_ARGS}"
