Xcode 8.3 beta 1 (8W109m)

diff --git a/Xcode.app/Contents/Developer/usr/libexec/git-core/git-stash b/Xcode.app/Contents/Developer/usr/libexec/git-core/git-stash
--- a/Xcode.app/Contents/Developer/usr/libexec/git-core/git-stash
+++ b/Xcode.app/Contents/Developer/usr/libexec/git-core/git-stash
@@ -77,7 +77,7 @@ git update-index -z --add --remove --stdin &&
 u_tree=$(git write-tree) &&
 printf 'untracked files on %s\n' "$msg" | git commit-tree $u_tree  &&
 rm -f "$TMPindex"
-) ) || die "Cannot save the untracked files"
+) ) || die "$(gettext "Cannot save the untracked files")"
 untracked_commit_option="-p $u_commit";
 else
 untracked_commit_option=
@@ -183,7 +183,7 @@ shift
 done
 if test -n "$patch_mode" && test -n "$untracked"
 then
-    die "Can't use --patch and --include-untracked or --all at the same time"
+die "$(gettext "Can't use --patch and --include-untracked or --all at the same time")"
 stash_msg="$*"
 git update-index -q --refresh
 if no_changes
@@ -277,8 +277,8 @@ w_tree=
 b_tree=
 i_tree=
 u_tree=
-REV=$(git rev-parse --no-flags --symbolic --sq "$@") || exit 1
 FLAGS=
+REV=
 for opt
 case "$opt" in
 -q|--quiet)
@@ -290,6 +290,7 @@ show_help
 test "$ALLOW_UNKNOWN_FLAGS" = t ||
 die "$(eval_gettext "unknown option: \$opt")"
 FLAGS="${FLAGS}${FLAGS:+ }$opt"
+REV="${REV}${REV:+ }'$opt'"
 esac
 done
 eval set -- $REV
@@ -297,6 +298,10 @@ case $# in
 have_stash || die "$(gettext "No stash found.")"
 set -- ${ref_stash}@{0}
 die "$(eval_gettext "Too many revisions specified: \$REV")"
+esac
+case "$1" in
+*[!0-9]*)
+set -- "${ref_stash}@{$1}"
 esac
 REV=$(git rev-parse --symbolic --verify --quiet "$1") || {
 reference="$1"
@@ -348,7 +353,7 @@ then
 GIT_INDEX_FILE="$TMPindex" git-read-tree "$u_tree" &&
 GIT_INDEX_FILE="$TMPindex" git checkout-index --all &&
 rm -f "$TMPindex" ||
-die 'Could not restore untracked files from stash'
+die "$(gettext "Could not restore untracked files from stash")"
 eval "
 GITHEAD_$w_tree='Stashed changes' &&
 GITHEAD_$c_tree='Updated upstream' &&
