Xcode 11.0 beta 5 (11M382q)

diff --git a/Xcode.app/Contents/Developer/usr/libexec/git-core/git-legacy-rebase b/Xcode.app/Contents/Developer/usr/libexec/git-core/git-legacy-rebase
--- a/Xcode.app/Contents/Developer/usr/libexec/git-core/git-legacy-rebase
+++ b/Xcode.app/Contents/Developer/usr/libexec/git-core/git-legacy-rebase
@@ -45,6 +45,7 @@ skip!              skip current patch and continue
 edit-todo!         edit the todo list during an interactive rebase
 quit!              abort but keep HEAD where it is
 show-current-patch! show the patch file being applied or merged
+reschedule-failed-exec automatically reschedule failed exec commands
 . git-sh-setup
 set_reflog_action rebase
 require_work_tree_exists
@@ -85,12 +86,15 @@ autosquash=
 keep_empty=
 allow_empty_message=--allow-empty-message
 signoff=
+reschedule_failed_exec=
 test "$(git config --bool rebase.autosquash)" = "true" && autosquash=t
 case "$(git config --bool commit.gpgsign)" in
 true)
 gpg_sign_opt=-S ;;
 gpg_sign_opt= ;;
 esac
+test "$(git config --bool rebase.reschedulefailedexec)" = "true" &&
+reschedule_failed_exec=--reschedule-failed-exec
 . git-rebase--common
 read_basic_state () {
 test -f "$state_dir/head-name" &&
@@ -106,7 +110,7 @@ orig_head=$(cat "$state_dir"/orig-head)
 else
 orig_head=$(cat "$state_dir"/head)
 fi &&
-GIT_QUIET=$(cat "$state_dir"/quiet) &&
+test -f "$state_dir"/quiet && GIT_QUIET=t
 test -f "$state_dir"/verbose && verbose=t
 test -f "$state_dir"/strategy && strategy="$(cat "$state_dir"/strategy)"
 test -f "$state_dir"/strategy_opts &&
@@ -118,6 +122,8 @@ gpg_sign_opt="$(cat "$state_dir"/gpg_sign_opt)"
 test -f "$state_dir"/signoff && {
 signoff="$(cat "$state_dir"/signoff)"
 force_rebase=t
+test -f "$state_dir"/reschedule-failed-exec &&
+reschedule_failed_exec=t
 finish_rebase () {
 rm -f "$(git rev-parse --git-path REBASE_HEAD)"
 apply_autostash &&
@@ -149,11 +155,12 @@ exec git rebase--interactive "$action" "$keep_empty" "$rebase_merges" "$rebase_c
 "$allow_empty_message" "$autosquash" "$verbose" \
 "$force_rebase" "$onto_name" "$head_name" "$strategy" \
 "$strategy_opts" "$cmd" "$switch_to" \
-"$allow_rerere_autoupdate" "$gpg_sign_opt" "$signoff"
+"$allow_rerere_autoupdate" "$gpg_sign_opt" "$signoff" \
+"$reschedule_failed_exec"
 run_specific_rebase () {
 if [ "$interactive_rebase" = implied ]; then
-GIT_EDITOR=:
-export GIT_EDITOR
+GIT_SEQUENCE_EDITOR=:
+export GIT_SEQUENCE_EDITOR
 autosquash=
 if test -n "$interactive_rebase" -a -z "$preserve_merges"
 then
@@ -189,6 +196,7 @@ type=am
 state_dir="$apply_dir"
 elif test -d "$merge_dir"
 then
+type=interactive
 if test -d "$merge_dir"/rewritten
 then
 type=preserve-merges
@@ -196,10 +204,7 @@ interactive_rebase=explicit
 preserve_merges=t
 elif test -f "$merge_dir"/interactive
 then
-type=interactive
 interactive_rebase=explicit
-else
-type=merge
 state_dir="$merge_dir"
 test -n "$type" && in_progress=t
 total_argc=$#
@@ -305,6 +310,10 @@ allow_rerere_autoupdate="$1"
 gpg_sign_opt=-S
 --gpg-sign=*)
 gpg_sign_opt="-S${1#--gpg-sign=}"
+--reschedule-failed-exec)
+reschedule_failed_exec=--reschedule-failed-exec
+--no-reschedule-failed-exec)
+reschedule_failed_exec=
 shift
 break
 usage
@@ -379,6 +388,7 @@ test -z "$interactive_rebase" && interactive_rebase=implied
 if test -n "$keep_empty"
 then
 test -z "$interactive_rebase" && interactive_rebase=implied
+actually_interactive=
 if test -n "$interactive_rebase"
 then
 if test -z "$preserve_merges"
@@ -386,10 +396,12 @@ then
 type=interactive
 else
 type=preserve-merges
+actually_interactive=t
 state_dir="$merge_dir"
 elif test -n "$do_merge"
 then
-type=merge
+interactive_rebase=implied
+type=interactive
 state_dir="$merge_dir"
 else
 type=am
@@ -397,22 +409,17 @@ state_dir="$apply_dir"
 if test -t 2 && test -z "$GIT_QUIET"
 then
 git_format_patch_opt="$git_format_patch_opt --progress"
-if test -n "$git_am_opt"; then
 incompatible_opts=$(echo " $git_am_opt " | \
     sed -e 's/ -q / /g' -e 's/^ \(.*\) $/\1/')
-if test -n "$interactive_rebase"
-then
 if test -n "$incompatible_opts"
 then
-die "$(gettext "error: cannot combine interactive options (--interactive, --exec, --rebase-merges, --preserve-merges, --keep-empty, --root + --onto) with am options ($incompatible_opts)")"
-if test -n "$do_merge"; then
-if test -n "$incompatible_opts"
+if test -n "$actually_interactive" || test "$do_merge"
 then
-die "$(gettext "error: cannot combine merge options (--merge, --strategy, --strategy-option) with am options ($incompatible_opts)")"
+die "$(gettext "fatal: cannot combine am options with either interactive or merge options")"
 if test -n "$signoff"
 then
 test -n "$preserve_merges" &&
-die "$(gettext "error: cannot combine '--signoff' with '--preserve-merges'")"
+die "$(gettext "fatal: cannot combine '--signoff' with '--preserve-merges'")"
 git_am_opt="$git_am_opt $signoff"
 force_rebase=t
 if test -n "$preserve_merges"
@@ -421,13 +428,15 @@ then
 # Note: incompatibility with --interactive is just a strong warning;
 #       git-rebase.txt caveats with "unless you know what you are doing"
 test -n "$rebase_merges" &&
-die "$(gettext "error: cannot combine '--preserve-merges' with '--rebase-merges'")"
+die "$(gettext "fatal: cannot combine '--preserve-merges' with '--rebase-merges'")"
+test -n "$reschedule_failed_exec" &&
+die "$(gettext "error: cannot combine '--preserve-merges' with '--reschedule-failed-exec'")"
 if test -n "$rebase_merges"
 then
 test -n "$strategy_opts" &&
-die "$(gettext "error: cannot combine '--rebase-merges' with '--strategy-option'")"
+die "$(gettext "fatal: cannot combine '--rebase-merges' with '--strategy-option'")"
 test -n "$strategy" &&
-die "$(gettext "error: cannot combine '--rebase-merges' with '--strategy'")"
+die "$(gettext "fatal: cannot combine '--rebase-merges' with '--strategy'")"
 if test -z "$rebase_root"
 then
 case "$#" in
@@ -528,7 +537,7 @@ require_clean_work_tree "rebase" "$(gettext "Please commit or stash them.")"
 # but this should be done only when upstream and onto are the same
 # and if this is not an interactive rebase.
 mb=$(git merge-base "$onto" "$orig_head")
-if test -z "$interactive_rebase" && test "$upstream" = "$onto" &&
+if test -z "$actually_interactive" && test "$upstream" = "$onto" &&
 test "$mb" = "$onto" && test -z "$restrict_revision" &&
 # linear history?
 ! (git rev-list --parents "$onto".."$orig_head" | sane_grep " .* ") > /dev/null
@@ -568,20 +577,23 @@ echo "$(eval_gettext "Changes from \$mb to \$onto:")"
 mb_tree="${mb:-$(git hash-object -t tree /dev/null)}"
 # We want color (if set), but no pager
 GIT_PAGER='' git diff --stat --summary "$mb_tree" "$onto"
+if test -z "$actually_interactive" && test "$mb" = "$orig_head"
+then
+say "$(eval_gettext "Fast-forwarded \$branch_name to \$onto_name.")"
+GIT_REFLOG_ACTION="$GIT_REFLOG_ACTION: checkout $onto_name" \
+git checkout -q "$onto^0" || die "could not detach HEAD"
+# If the $onto is a proper descendant of the tip of the branch, then
+# we just fast-forwarded.
+git update-ref ORIG_HEAD $orig_head
+move_to_original_branch
+finish_rebase
+exit 0
 test -n "$interactive_rebase" && run_specific_rebase
 # Detach HEAD and reset the tree
 say "$(gettext "First, rewinding head to replay your work on top of it...")"
 GIT_REFLOG_ACTION="$GIT_REFLOG_ACTION: checkout $onto_name" \
 git checkout -q "$onto^0" || die "could not detach HEAD"
 git update-ref ORIG_HEAD $orig_head
-# If the $onto is a proper descendant of the tip of the branch, then
-# we just fast-forwarded.
-if test "$mb" = "$orig_head"
-then
-say "$(eval_gettext "Fast-forwarded \$branch_name to \$onto_name.")"
-move_to_original_branch
-finish_rebase
-exit 0
 if test -n "$rebase_root"
 then
 revisions="$onto..$orig_head"
