Xcode 9.3 beta 1 (9Q98q)

diff --git a/Xcode.app/Contents/Developer/usr/libexec/git-core/git-filter-branch b/Xcode.app/Contents/Developer/usr/libexec/git-core/git-filter-branch
--- a/Xcode.app/Contents/Developer/usr/libexec/git-core/git-filter-branch
+++ b/Xcode.app/Contents/Developer/usr/libexec/git-core/git-filter-branch
@@ -51,12 +51,12 @@ set_ident () {
 parse_ident_from_commit author AUTHOR committer COMMITTER
 finish_ident AUTHOR
 finish_ident COMMITTER
-USAGE="[--setup <command>] [--env-filter <command>]
+USAGE="[--setup <command>] [--subdirectory-filter <directory>] [--env-filter <command>]
 [--tree-filter <command>] [--index-filter <command>]
 [--parent-filter <command>] [--msg-filter <command>]
 [--commit-filter <command>] [--tag-name-filter <command>]
-[--subdirectory-filter <directory>] [--original <namespace>]
-[-d <directory>] [-f | --force]
+[--original <namespace>]
+[-d <directory>] [-f | --force] [--state-branch <branch>]
 [--] [<rev-list options>...]"
 OPTIONS_SPEC=
 . git-sh-setup
@@ -72,6 +72,7 @@ filter_msg=cat
 filter_commit=
 filter_tag_name=
 filter_subdir=
+state_branch=
 orig_namespace=refs/original/
 force=
 prune_empty=
@@ -105,6 +106,9 @@ case "$ARG" in
 tempdir="$OPTARG"
 --setup)
 filter_setup="$OPTARG"
+--subdirectory-filter)
+filter_subdir="$OPTARG"
+remap_to_ancestor=t
 --env-filter)
 filter_env="$OPTARG"
 --tree-filter)
@@ -119,11 +123,10 @@ filter_msg="$OPTARG"
 filter_commit="$functions; $OPTARG"
 --tag-name-filter)
 filter_tag_name="$OPTARG"
---subdirectory-filter)
-filter_subdir="$OPTARG"
-remap_to_ancestor=t
 --original)
 orig_namespace=$(expr "$OPTARG/" : '\(.*[^/]\)/*$')/
+--state-branch)
+state_branch="$OPTARG"
 usage
 esac
 done
@@ -148,6 +151,12 @@ trap 'cd "$orig_dir"; rm -rf "$tempdir"' 0
 ORIG_GIT_DIR="$GIT_DIR"
 ORIG_GIT_WORK_TREE="$GIT_WORK_TREE"
 ORIG_GIT_INDEX_FILE="$GIT_INDEX_FILE"
+ORIG_GIT_AUTHOR_NAME="$GIT_AUTHOR_NAME"
+ORIG_GIT_AUTHOR_EMAIL="$GIT_AUTHOR_EMAIL"
+ORIG_GIT_AUTHOR_DATE="$GIT_AUTHOR_DATE"
+ORIG_GIT_COMMITTER_NAME="$GIT_COMMITTER_NAME"
+ORIG_GIT_COMMITTER_EMAIL="$GIT_COMMITTER_EMAIL"
+ORIG_GIT_COMMITTER_DATE="$GIT_COMMITTER_DATE"
 GIT_WORK_TREE=.
 export GIT_DIR GIT_WORK_TREE
 # Make sure refs/original is empty
@@ -172,6 +181,22 @@ GIT_INDEX_FILE="$(pwd)/../index"
 export GIT_INDEX_FILE
 # map old->new commit ids for rewriting parents
 mkdir ../map || die "Could not create map/ directory"
+if test -n "$state_branch"
+then
+state_commit=$(git rev-parse --no-flags --revs-only "$state_branch")
+if test -n "$state_commit"
+then
+echo "Populating map from $state_branch ($state_commit)" 1>&2
+perl -e'open(MAP, "-|", "git show $ARGV[0]:filter.map") or die;
+while (<MAP>) {
+m/(.*):(.*)/ or die;
+open F, ">../map/$1" or die;
+print F "$2" or die;
+close(F) or die;
+close(MAP) or die;' "$state_commit" \
+|| die "Unable to load state from $state_branch:filter.map"
+else
+echo "Branch $state_branch does not exist. Will create" 1>&2
 # we need "--" only if there are no path arguments in $@
 nonrevs=$(git rev-parse --no-revs "$@") || exit
 if test -z "$nonrevs"
@@ -375,7 +400,7 @@ sed -n \
 }' \
     -e '/^-----BEGIN PGP SIGNATURE-----/q' \
     -e 'p' ) |
-git mktag) ||
+git hash-object -t tag -w --stdin) ||
 die "Could not create new tag object for $ref"
 if git cat-file tag "$ref" | \
    sane_grep '^-----BEGIN PGP SIGNATURE-----' >/dev/null 2>&1
@@ -384,10 +409,9 @@ warn "gpg signature stripped from tag object $sha1t"
 git update-ref "refs/tags/$new_ref" "$new_sha1" ||
 die "Could not write tag $new_ref"
 done
-cd "$orig_dir"
-rm -rf "$tempdir"
-trap - 0
 unset GIT_DIR GIT_WORK_TREE GIT_INDEX_FILE
+unset GIT_AUTHOR_NAME GIT_AUTHOR_EMAIL GIT_AUTHOR_DATE
+unset GIT_COMMITTER_NAME GIT_COMMITTER_EMAIL GIT_COMMITTER_DATE
 test -z "$ORIG_GIT_DIR" || {
 GIT_DIR="$ORIG_GIT_DIR" && export GIT_DIR
 test -z "$ORIG_GIT_WORK_TREE" || {
@@ -396,6 +420,46 @@ export GIT_WORK_TREE
 test -z "$ORIG_GIT_INDEX_FILE" || {
 GIT_INDEX_FILE="$ORIG_GIT_INDEX_FILE" &&
 export GIT_INDEX_FILE
+test -z "$ORIG_GIT_AUTHOR_NAME" || {
+GIT_AUTHOR_NAME="$ORIG_GIT_AUTHOR_NAME" &&
+export GIT_AUTHOR_NAME
+test -z "$ORIG_GIT_AUTHOR_EMAIL" || {
+GIT_AUTHOR_EMAIL="$ORIG_GIT_AUTHOR_EMAIL" &&
+export GIT_AUTHOR_EMAIL
+test -z "$ORIG_GIT_AUTHOR_DATE" || {
+GIT_AUTHOR_DATE="$ORIG_GIT_AUTHOR_DATE" &&
+export GIT_AUTHOR_DATE
+test -z "$ORIG_GIT_COMMITTER_NAME" || {
+GIT_COMMITTER_NAME="$ORIG_GIT_COMMITTER_NAME" &&
+export GIT_COMMITTER_NAME
+test -z "$ORIG_GIT_COMMITTER_EMAIL" || {
+GIT_COMMITTER_EMAIL="$ORIG_GIT_COMMITTER_EMAIL" &&
+export GIT_COMMITTER_EMAIL
+test -z "$ORIG_GIT_COMMITTER_DATE" || {
+GIT_COMMITTER_DATE="$ORIG_GIT_COMMITTER_DATE" &&
+export GIT_COMMITTER_DATE
+if test -n "$state_branch"
+then
+echo "Saving rewrite state to $state_branch" 1>&2
+state_blob=$(
+perl -e'opendir D, "../map" or die;
+open H, "|-", "git hash-object -w --stdin" or die;
+foreach (sort readdir(D)) {
+next if m/^\.\.?$/;
+open F, "<../map/$_" or die;
+chomp($f = <F>);
+print H "$_:$f\n" or die;
+close(H) or die;' || die "Unable to save state")
+state_tree=$(/bin/echo -e "100644 blob $state_blob\tfilter.map" | git mktree)
+if test -n "$state_commit"
+then
+state_commit=$(/bin/echo "Sync" | git commit-tree "$state_tree" -p "$state_commit")
+else
+state_commit=$(/bin/echo "Sync" | git commit-tree "$state_tree" )
+git update-ref "$state_branch" "$state_commit"
+cd "$orig_dir"
+rm -rf "$tempdir"
+trap - 0
 if [ "$(is_bare_repository)" = false ]; then
 git read-tree -u -m HEAD || exit
 exit 0
