Xcode 10.0 beta 3 (10L201y)

diff --git a/Xcode.app/Contents/Developer/usr/libexec/git-core/git-bisect b/Xcode.app/Contents/Developer/usr/libexec/git-core/git-bisect
--- a/Xcode.app/Contents/Developer/usr/libexec/git-core/git-bisect
+++ b/Xcode.app/Contents/Developer/usr/libexec/git-core/git-bisect
@@ -1,5 +1,5 @@
 #!/bin/sh
-USAGE='[help|start|bad|good|new|old|terms|skip|next|reset|visualize|replay|log|run]'
+USAGE='[help|start|bad|good|new|old|terms|skip|next|reset|visualize|view|replay|log|run]'
 LONG_USAGE='git bisect help
 print this long help message.
 git bisect start [--term-{old,good}=<term> --term-{new,bad}=<term>]
@@ -19,7 +19,7 @@ git bisect next
 find next bisection to test and check it out.
 git bisect reset [<commit>]
 finish bisection search and go back to commit.
-git bisect visualize
+git bisect (visualize|view)
 show bisect status in gitk.
 git bisect replay <logfile>
 replay bisection log.
@@ -149,13 +149,13 @@ start_head="${head#refs/heads/}"
 die "$(gettext "Bad HEAD - strange symbolic ref")"
 esac
 # Get rid of any old bisect state.
-bisect_clean_state || exit
+git bisect--helper --bisect-clean-state || exit
 # Change state.
 # In case of mistaken revs or checkout error, or signals received,
 # "bisect_auto_next" below may exit or misbehave.
 # We have to trap this to be able to clean up using
 # "bisect_clean_state".
-trap 'bisect_clean_state' 0
+trap 'git bisect--helper --bisect-clean-state' 0
 trap 'exit 255' 1 2 3 15
 # Write new start state.
 echo "$start_head" >"$GIT_DIR/BISECT_START" && {
@@ -166,7 +166,7 @@ git rev-parse --sq-quote "$@" >"$GIT_DIR/BISECT_NAMES" &&
 eval "$eval true" &&
 if test $must_write_terms -eq 1
 then
-write_terms "$TERM_BAD" "$TERM_GOOD"
+git bisect--helper --write-terms "$TERM_BAD" "$TERM_GOOD" || exit
 fi &&
 echo "git bisect start$orig_args" >>"$GIT_DIR/BISECT_LOG" || exit
 # Check if we can proceed to the next bisect state.
@@ -186,17 +186,6 @@ esac
 git update-ref "refs/bisect/$tag" "$rev" || exit
 echo "# $state: $(git show-branch $rev)" >>"$GIT_DIR/BISECT_LOG"
 test -n "$nolog" || echo "git bisect $state $rev" >>"$GIT_DIR/BISECT_LOG"
-is_expected_rev() {
-test -f "$GIT_DIR/BISECT_EXPECTED_REV" &&
-test "$1" = $(cat "$GIT_DIR/BISECT_EXPECTED_REV")
-check_expected_revs() {
-for _rev in "$@"; do
-if ! is_expected_rev "$_rev"
-then
-rm -f "$GIT_DIR/BISECT_ANCESTORS_OK"
-rm -f "$GIT_DIR/BISECT_EXPECTED_REV"
-return
-done
 bisect_skip() {
 all=''
 for arg in "$@"
@@ -220,7 +209,7 @@ bisected_head=$(bisect_head)
 rev=$(git rev-parse --verify "$bisected_head") ||
 die "$(eval_gettext "Bad rev input: \$bisected_head")"
 bisect_write "$state" "$rev"
-check_expected_revs "$rev" ;;
+git bisect--helper --check-expected-revs "$rev" ;;
 2,"$TERM_BAD"|*,"$TERM_GOOD"|*,skip)
 shift
 hash_list=''
@@ -232,7 +221,7 @@ done
 for rev in $hash_list
 bisect_write "$state" "$rev"
 done
-check_expected_revs $hash_list ;;
+git bisect--helper --check-expected-revs $hash_list ;;
 *,"$TERM_BAD")
 die "$(eval_gettext "'git bisect \$TERM_BAD' can take only one argument.")" ;;
 usage ;;
@@ -333,24 +322,7 @@ if ! test -f "$GIT_DIR/BISECT_HEAD" && ! git checkout "$branch" --
 then
 die "$(eval_gettext "Could not check out original HEAD '\$branch'.
 Try 'git bisect reset <commit>'.")"
-bisect_clean_state
-bisect_clean_state() {
-# There may be some refs packed during bisection.
-git for-each-ref --format='%(refname) %(objectname)' refs/bisect/\* |
-while read ref hash
-git update-ref -d $ref $hash || exit
-done
-rm -f "$GIT_DIR/BISECT_EXPECTED_REV" &&
-rm -f "$GIT_DIR/BISECT_ANCESTORS_OK" &&
-rm -f "$GIT_DIR/BISECT_LOG" &&
-rm -f "$GIT_DIR/BISECT_NAMES" &&
-rm -f "$GIT_DIR/BISECT_RUN" &&
-rm -f "$GIT_DIR/BISECT_TERMS" &&
-# Cleanup head-name if it got left by an old version of git-bisect
-rm -f "$GIT_DIR/head-name" &&
-git update-ref -d --no-deref BISECT_HEAD &&
-# clean up BISECT_START last
-rm -f "$GIT_DIR/BISECT_START"
+git bisect--helper --bisect-clean-state || exit
 bisect_replay () {
 file="$1"
 test "$#" -eq 1 || die "$(gettext "No logfile given")"
@@ -378,6 +350,7 @@ done <"$file"
 bisect_auto_next
 bisect_run () {
 bisect_next_check fail
+test -n "$*" || die "$(gettext "bisect run failed: no command provided.")"
 while true
 command="$@"
 eval_gettextln "running \$command"
@@ -427,35 +400,6 @@ then
 read TERM_BAD
 read TERM_GOOD
 } <"$GIT_DIR/BISECT_TERMS"
-write_terms () {
-TERM_BAD=$1
-TERM_GOOD=$2
-if test "$TERM_BAD" = "$TERM_GOOD"
-then
-die "$(gettext "please use two different terms")"
-check_term_format "$TERM_BAD" bad
-check_term_format "$TERM_GOOD" good
-printf '%s\n%s\n' "$TERM_BAD" "$TERM_GOOD" >"$GIT_DIR/BISECT_TERMS"
-check_term_format () {
-term=$1
-git check-ref-format refs/bisect/"$term" ||
-die "$(eval_gettext "'\$term' is not a valid term")"
-case "$term" in
-help|start|terms|skip|next|reset|visualize|replay|log|run)
-die "$(eval_gettext "can't use the builtin command '\$term' as a term")"
-bad|new)
-if test "$2" != bad
-then
-# In theory, nothing prevents swapping
-# completely good and bad, but this situation
-# could be confusing and hasn't been tested
-# enough. Forbid it for now.
-die "$(eval_gettext "can't change the meaning of term '\$term'")"
-good|old)
-if test "$2" != good
-then
-die "$(eval_gettext "can't change the meaning of term '\$term'")"
-esac
 check_and_set_terms () {
 cmd="$1"
 case "$cmd" in
@@ -467,11 +411,15 @@ case "$cmd" in
 bad|good)
 if ! test -s "$GIT_DIR/BISECT_TERMS"
 then
-write_terms bad good
+TERM_BAD=bad
+TERM_GOOD=good
+git bisect--helper --write-terms "$TERM_BAD" "$TERM_GOOD" || exit
 new|old)
 if ! test -s "$GIT_DIR/BISECT_TERMS"
 then
-write_terms new old
+TERM_BAD=new
+TERM_GOOD=old
+git bisect--helper --write-terms "$TERM_BAD" "$TERM_GOOD" || exit
 esac ;;
 esac
 bisect_voc () {
