Xcode 8.2 (8C38)

diff --git a/Xcode.app/Contents/Developer/usr/libexec/git-core/git-submodule b/Xcode.app/Contents/Developer/usr/libexec/git-core/git-submodule
--- a/Xcode.app/Contents/Developer/usr/libexec/git-core/git-submodule
+++ b/Xcode.app/Contents/Developer/usr/libexec/git-core/git-submodule
@@ -6,14 +6,13 @@ USAGE="[--quiet] add [-b <branch>] [-f|--force] [--name <name>] [--reference <re
    or: $dashless [--quiet] status [--cached] [--recursive] [--] [<path>...]
    or: $dashless [--quiet] init [--] [<path>...]
    or: $dashless [--quiet] deinit [-f|--force] (--all| [--] <path>...)
-   or: $dashless [--quiet] update [--init] [--remote] [-N|--no-fetch] [-f|--force] [--checkout|--merge|--rebase] [--reference <repository>] [--recursive] [--] [<path>...]
+   or: $dashless [--quiet] update [--init] [--remote] [-N|--no-fetch] [-f|--force] [--checkout|--merge|--rebase] [--[no-]recommend-shallow] [--reference <repository>] [--recursive] [--] [<path>...]
    or: $dashless [--quiet] summary [--cached|--files] [--summary-limit <n>] [commit] [--] [<path>...]
    or: $dashless [--quiet] foreach [--recursive] <command>
    or: $dashless [--quiet] sync [--recursive] [--] [<path>...]"
 OPTIONS_SPEC=
 SUBDIRECTORY_OK=Yes
 . git-sh-setup
-. git-sh-i18n
 . git-parse-remote
 require_work_tree
 wt_prefix=$(git rev-parse --show-prefix)
@@ -42,7 +41,7 @@ depth=
 die_if_unmatched ()
 if test "$1" = "#unmatched"
 then
-exit 1
+exit ${2:-1}
 # Print a submodule configuration setting
 # $1 = submodule name
 # $2 = option name
@@ -172,14 +171,15 @@ if test -d ".git/modules/$sm_name"
 then
 if test -z "$force"
 then
-echo >&2 "$(eval_gettext "A git directory for '\$sm_name' is found locally with remote(s):")"
+eval_gettextln >&2 "A git directory for '\$sm_name' is found locally with remote(s):"
 GIT_DIR=".git/modules/$sm_name" GIT_WORK_TREE=. git remote -v | grep '(fetch)' | sed -e s,^,"  ", -e s,' (fetch)',, >&2
-echo >&2 "$(eval_gettext "If you want to reuse this local git directory instead of cloning again from")"
-echo >&2 "  $realrepo"
-echo >&2 "$(eval_gettext "use the '--force' option. If the local git directory is not the correct repo")"
-die "$(eval_gettext "or you are unsure what this means choose another name with the '--name' option.")"
+die "$(eval_gettextln "\
+If you want to reuse this local git directory instead of cloning again from
+  \$realrepo
+use the '--force' option. If the local git directory is not the correct repo
+or you are unsure what this means choose another name with the '--name' option.")"
 else
-echo "$(eval_gettext "Reactivating local git directory for submodule '\$sm_name'.")"
+eval_gettextln "Reactivating local git directory for submodule '\$sm_name'."
 git submodule--helper clone ${GIT_QUIET:+--quiet} --prefix "$wt_prefix" --path "$sm_path" --name "$sm_name" --url "$realrepo" ${reference:+"$reference"} ${depth:+"$depth"} || exit
 sanitize_submodule_env
 cd "$sm_path" &&
@@ -221,9 +221,9 @@ toplevel=$(pwd)
 # command in the subshell (and a recursive call to this function)
 exec 3<&0
 git submodule--helper list --prefix "$wt_prefix" ||
-echo "#unmatched"
+echo "#unmatched" $?
 while read mode sha1 stage sm_path
-die_if_unmatched "$mode"
+die_if_unmatched "$mode" "$sha1"
 if test -e "$sm_path"/.git
 then
 displaypath=$(git submodule--helper relative-path "$prefix$sm_path" "$wt_prefix")
@@ -290,9 +290,9 @@ if test $# = 0 && test -z "$deinit_all"
 then
 die "$(eval_gettext "Use '--all' if you really want to deinitialize all submodules")"
 git submodule--helper list --prefix "$wt_prefix" "$@" ||
-echo "#unmatched"
+echo "#unmatched" $?
 while read mode sha1 stage sm_path
-die_if_unmatched "$mode"
+die_if_unmatched "$mode" "$sha1"
 name=$(git submodule--helper name "$sm_path") || exit
 displaypath=$(git submodule--helper relative-path "$sm_path" "$wt_prefix")
 # Remove the submodule work tree (unless the user already did it)
@@ -301,8 +301,9 @@ then
 # Protect submodules containing a .git directory
 if test -d "$sm_path/.git"
 then
-echo >&2 "$(eval_gettext "Submodule work tree '\$displaypath' contains a .git directory")"
-die "$(eval_gettext "(use 'rm -rf' if you really want to remove it including all of its history)")"
+die "$(eval_gettext "\
+Submodule work tree '\$displaypath' contains a .git directory
+(use 'rm -rf' if you really want to remove it including all of its history)")"
 if test -z "$force"
 then
 git rm -qn "$sm_path" ||
@@ -330,7 +331,8 @@ sanitize_submodule_env &&
 cd "$1" &&
 case "$2" in
 git fetch ;;
-git fetch $(get_default_remote) "$2" ;;
+shift
+git fetch $(get_default_remote) "$@" ;;
 esac
 # Update each submodule path to correct revision, using clone and checkout as needed
 # $@ = requested paths (default to all)
@@ -362,6 +364,10 @@ update="merge"
 recursive=1
 --checkout)
 update="checkout"
+--recommend-shallow)
+recommend_shallow="--recommend-shallow"
+--no-recommend-shallow)
+recommend_shallow="--no-recommend-shallow"
 --depth)
 case "$2" in '') usage ;; esac
 depth="--depth=$2"
@@ -390,15 +396,15 @@ ${prefix:+--recursive-prefix "$prefix"} \
 ${update:+--update "$update"} \
 ${reference:+--reference "$reference"} \
 ${depth:+--depth "$depth"} \
+${recommend_shallow:+"$recommend_shallow"} \
 ${jobs:+$jobs} \
-"$@" || echo "#unmatched"
+"$@" || echo "#unmatched" $?
 } | {
 err=
 while read mode sha1 stage just_cloned sm_path
-die_if_unmatched "$mode"
+die_if_unmatched "$mode" "$sha1"
 name=$(git submodule--helper name "$sm_path") || exit
 url=$(git config submodule."$name".url)
-branch=$(get_submodule_config "$name" branch master)
 if ! test -z "$update"
 then
 update_module=$update
@@ -418,15 +424,16 @@ git rev-parse --verify HEAD) ||
 die "$(eval_gettext "Unable to find current revision in submodule path '\$displaypath'")"
 if test -n "$remote"
 then
+branch=$(git submodule--helper remote-branch "$sm_path")
 if test -z "$nofetch"
 then
 # Fetch remote before determining tracking $sha1
-(sanitize_submodule_env; cd "$sm_path" && git-fetch) ||
+fetch_in_submodule "$sm_path" $depth ||
 die "$(eval_gettext "Unable to fetch in submodule path '\$sm_path'")"
 remote_name=$(sanitize_submodule_env; cd "$sm_path" && get_default_remote)
 sha1=$(sanitize_submodule_env; cd "$sm_path" &&
 git rev-parse --verify "${remote_name}/${branch}") ||
-die "$(eval_gettext "Unable to find current ${remote_name}/${branch} revision in submodule path '\$sm_path'")"
+die "$(eval_gettext "Unable to find current \${remote_name}/\${branch} revision in submodule path '\$sm_path'")"
 if test "$subsha1" != "$sha1" || test -n "$force"
 then
 subforce=$force
@@ -439,13 +446,13 @@ then
 # Run fetch only if $sha1 isn't present or it
 # is not reachable from a ref.
 is_tip_reachable "$sm_path" "$sha1" ||
-fetch_in_submodule "$sm_path" ||
+fetch_in_submodule "$sm_path" $depth ||
 die "$(eval_gettext "Unable to fetch in submodule path '\$displaypath'")"
 # Now we tried the usual fetch, but $sha1 may
 # not be reachable from any of the refs
 is_tip_reachable "$sm_path" "$sha1" ||
-fetch_in_submodule "$sm_path" "$sha1" ||
-die "$(eval_gettext "Fetched in submodule path '\$displaypath', but it did not contain $sha1. Direct fetching of that commit failed.")"
+fetch_in_submodule "$sm_path" $depth "$sha1" ||
+die "$(eval_gettext "Fetched in submodule path '\$displaypath', but it did not contain \$sha1. Direct fetching of that commit failed.")"
 must_die_on_failure=
 case "$update_module" in
 checkout)
@@ -488,7 +495,7 @@ res=$?
 if test $res -gt 0
 then
 die_msg="$(eval_gettext "Failed to recurse into submodule path '\$displaypath'")"
-if test $res -eq 1
+if test $res -ne 2
 then
 err="${err};$die_msg"
 continue
@@ -693,9 +700,9 @@ esac
 shift
 done
 git submodule--helper list --prefix "$wt_prefix" "$@" ||
-echo "#unmatched"
+echo "#unmatched" $?
 while read mode sha1 stage sm_path
-die_if_unmatched "$mode"
+die_if_unmatched "$mode" "$sha1"
 name=$(git submodule--helper name "$sm_path") || exit
 url=$(git config submodule."$name".url)
 displaypath=$(git submodule--helper relative-path "$prefix$sm_path" "$wt_prefix")
@@ -749,9 +756,9 @@ esac
 done
 cd_to_toplevel
 git submodule--helper list --prefix "$wt_prefix" "$@" ||
-echo "#unmatched"
+echo "#unmatched" $?
 while read mode sha1 stage sm_path
-die_if_unmatched "$mode"
+die_if_unmatched "$mode" "$sha1"
 name=$(git submodule--helper name "$sm_path")
 url=$(git config -f .gitmodules --get submodule."$name".url)
 # Possibly a url relative to parent
