Xcode 9.2 beta 1 (9C32c)

diff --git a/Xcode.app/Contents/Developer/usr/libexec/git-core/git-stash b/Xcode.app/Contents/Developer/usr/libexec/git-core/git-stash
--- a/Xcode.app/Contents/Developer/usr/libexec/git-core/git-stash
+++ b/Xcode.app/Contents/Developer/usr/libexec/git-core/git-stash
@@ -34,9 +34,14 @@ git diff-index --quiet --cached HEAD --ignore-submodules -- "$@" &&
 git diff-files --quiet --ignore-submodules -- "$@" &&
 (test -z "$untracked" || test -z "$(untracked_files)")
 untracked_files () {
+if test "$1" = "-z"
+then
+shift
+z=-z
+else
 excl_opt=--exclude-standard
 test "$untracked" = "all" && excl_opt=
-git ls-files -o -z $excl_opt -- "$@"
+git ls-files -o $z $excl_opt -- "$@"
 clear_stash () {
 if test $# != 0
 then
@@ -86,7 +91,7 @@ then
 # Untracked files are stored by themselves in a parentless commit, for
 # ease of unpacking later.
 u_commit=$(
-untracked_files "$@" | (
+untracked_files -z "$@" | (
 GIT_INDEX_FILE="$TMPindex" &&
 export GIT_INDEX_FILE &&
 rm -f "$TMPindex" &&
@@ -345,7 +350,7 @@ esac
 done
 eval set -- $REV
 case $# in
-have_stash || die "$(gettext "No stash found.")"
+have_stash || die "$(gettext "No stash entries found.")"
 set -- ${ref_stash}@{0}
 die "$(eval_gettext "Too many revisions specified: \$REV")"
 esac
@@ -400,10 +405,10 @@ die "$(gettext "Could not save index tree")"
 git reset
 if test -n "$u_tree"
 then
-GIT_INDEX_FILE="$TMPindex" git-read-tree "$u_tree" &&
+GIT_INDEX_FILE="$TMPindex" git read-tree "$u_tree" &&
 GIT_INDEX_FILE="$TMPindex" git checkout-index --all &&
 rm -f "$TMPindex" ||
-die "$(gettext "Could not restore untracked files from stash")"
+die "$(gettext "Could not restore untracked files from stash entry")"
 eval "
 GITHEAD_$w_tree='Stashed changes' &&
 GITHEAD_$c_tree='Updated upstream' &&
@@ -445,7 +450,7 @@ then
 drop_stash "$@"
 else
 status=$?
-say "$(gettext "The stash is kept in case you need it again.")"
+say "$(gettext "The stash entry is kept in case you need it again.")"
 exit $status
 drop_stash () {
 assert_stash_ref "$@"
