Xcode 9.0 beta 1 (9M136h)

diff --git a/Xcode.app/Contents/Developer/usr/share/xcs/xcsd/bin/test b/Xcode.app/Contents/Developer/usr/share/xcs/xcsd/bin/test
--- a/Xcode.app/Contents/Developer/usr/share/xcs/xcsd/bin/test
+++ b/Xcode.app/Contents/Developer/usr/share/xcs/xcsd/bin/test
@@ -1,8 +1,17 @@
 #!/bin/bash
+unset LANG
 pkill -9 -u `whoami` redis-server
 pkill -9 -u `whoami` beam.smp
 DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
 cd $DIR/..
+if [ -z "$XCSSECURITY_PATH" ]; then
+    export XCSSECURITY_PATH=`xcrun -f xcssecurity`
+if [ -z "$XCSSECURITY_PATH" ]; then
+    echo "error: couldn't find xcssecurity. Dumping env" >&2
+    env >&2
+    exit 1
+else
+    echo "Found xcssecurity at $XCSSECURITY_PATH" >&2
 # Paths
 xcode_path=`xcode-select -p`
 xcs_path="${xcode_path}/usr/share/xcs"
@@ -22,6 +31,7 @@ rm -rf "${testdir_path}"
 mkdir -p "$redis_db_path"
 mkdir -p "$couchdb_db_path"
 mkdir -p "$testdir_path/CodeCoverageCache"
+mkdir -p "$testdir_path/ProvisioningProfiles"
 cat >"$couchdb_conf_path" <<COUCHDB_CONF
 [couchdb]
 database_dir = ${couchdb_db_path}
